name: test

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  test:
    # runs-on: ubuntu-latest
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3

      - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3

    - name: Install composer dependencies
      run: |
        composer install --no-scripts

    - name: Run Test suite
      run: php artisan test